### ISSUE TITLE
why ShortCutDirectiveFactory has no rootnamespace?

### ISSUE THREAD

**Issue by konne** [q2g/daVinci.js#13]
https://github.com/q2g/daVinci.js/blob/master/src/directives/extensionHeader.ts#L188

if we have 2 extensions with different versions of ShortCutDirective we can get in trouble

**Comment by thomashaenig** [comment]
Hi, 
the shortcut directive does not need the rootnamespace, cause it does not call any other directive. The rootnamespace is only required when the directive them self can call other directives in there template, to ensure the multiuse of the called directives.

**Comment by konne** [comment]
Hi,
just try to load 2 diffetent versions of the shortcut directive in one html app and this will not work.

**Comment by r-hannuschka** [comment]
@konne we can't reproduce this Problem, can u provide more informations or an simple example ?

 Every directive we used in out extension is registrated with q2g<RootNamespace><DirectiveName>Directive.

I think it could only happens if u use 2 times the "same" extension with diffrent versions and diffrent version of davinci.js.  Then i would say the namespace will collide but not only for the shortcut directive.

Greeetings

**Comment by r-hannuschka** [comment]
closed allready
