### ISSUE TITLE
searchBar - remove watcher + direct registration

### ISSUE THREAD

**Issue by konne** [q2g/daVinci.js#17]
https://github.com/q2g/daVinci.js/blob/master/src/directives/searchBar.ts#L32

please change to direct onfocus & direct onvisible on the html element without watcher

**Comment by thomashaenig** [comment]
I tried to implement the requested changes, unfortunately it is not possible to register on those events. After an online search, the watcher solutions seem to be the best solution. 

On alternative could be to use the ngIf and not ngShow, and try to look on the “display” property. The problem is, that it seems to be a bug in angular according to isolate scope in own directive with a ngIf around. I will try to take a closer look at this point.

**Comment by konne** [comment]
Why this is not working:

object.addEventListener ("focus", handler, useCapture); 
object.attachEvent ("onfocus", handler);

**Comment by thomashaenig** [comment]
It is not possible to trigger the focus event on the div element where it needs to be trigged. There are some workarounds to achieve this, or a similar event, but these are not good in my imagination.

**Comment by konne** [comment]
thanks for explanation
