### ISSUE TITLE
shortcut - rework actions

### ISSUE THREAD

**Issue by konne** [q2g/daVinci.js#8]
1. you can also trigger the focus with triggerHandler("focus") -> reduce code
2. why onClick -> click

3. discuss new attribute for shortcut item like triggerHandler = true, so that the action is just send 1:1 to the element.triggerHandler and not to external Action Handler to make is more universal

**Comment by thomashaenig** [comment]
1. and 2. is solved
3.  i am not quite sure if i do understand this point correctly. I think a new attribute would be very useful, especially for performance reasons, so that you only register the handlers when the actual focused position does require these handler. This would require some deeper changes in the code. So, if my understanding is correct, i would suggest to change the third point to a "performance enhancement".

**Comment by konne** [comment]
please to it with 2 attributes -> perfomance in separate ticket #21
